### ISSUE TITLE
Number of channels for model input

### ISSUE THREAD

**Issue by kalpa61** [Nikki-Gu/MEMix#4]
Encountered a code bug when replicating, specifically, the Vit model expected input channel is 2, but the input channel is 3, the source code missing the intermediate processing part? The following is the program error:

>  Traceback (most recent call last):
>   File "D:\PycharmProject\MEMix\main.py", line 239, in <module>
>     run_training(cut_alpha=2.0, mix_alpha=1.0,num_classes=5)
>   File "D:\PycharmProject\MEMix\main.py", line 124, in run_training
>     ALL, attn, final = net_all(mix_flow, onset)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\PycharmProject\MEMix\model.py", line 272, in forward
>     x = self.model(x,y)  # [B,768]
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\PycharmProject\MEMix\model.py", line 201, in forward
>     x = self.forward_features(x,y)
>   File "D:\PycharmProject\MEMix\model.py", line 175, in forward_features
>     x = self.patch_embed(x)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\timm\layers\patch_embed.py", line 131, in forward
>     x = self.proj(x)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [768, 2, 16, 16], expected input[34, 3, 224, 224] to have 2 channels, but got 3 channels instead

**Comment by GaoCL457** [comment]
> 复制时遇到代码错误，具体来说，Vit模型的预期输入通道是2，但输入通道是3，源代码缺少中间处理部分？以下是程序错误：
> 
> > 回溯（最近一次通话）：文件“D:\PycharmProject\MEMix\main.py”，第239行，在运行_训练（cut_alpha=2.0，mix_alpha=1.0，num_classes=5）文件“D:\PycharmProject\MEMix\main.py”，第124行，在run_training中ALL, attn, final = net_all(mix_flow, onset)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\PycharmProject\MEMix\model.py”，第272行，向前x = 自我.模型(x,y) # [B,768]文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\PycharmProject\MEMix\model.py”，第201行，向前X = 自我.前进_特征(x,y)文件“D:\PycharmProject\MEMix\model.py”，第175行，在forward_features中X = 自我.补丁_嵌入(x)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\Anaconda3\envs\Mers\lib\site-packages\timm\layers\patch_embed.py”，第131行，向前X = 自我.proj(x)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py”，第460行，向前返回self._conv_forward（输入，自我.权重，自我.偏置）文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py”，第456行，在_conv_forward中返回F.conv2d（输入，重量，偏置，自我。步幅，运行时错误：给定组=1，大小权重[768，2，16，16]，预期输入[34，3，224，224]有2个通道，但得到了3个通道

我也遇到了这个问题，请问你解决了吗

**Comment by GaoCL457** [comment]
> 复制时遇到代码错误，具体来说，Vit模型的预期输入通道是2，但输入通道是3，源代码缺少中间处理部分？以下是程序错误：
> 
> > 回溯（最近一次通话）：文件“D:\PycharmProject\MEMix\main.py”，第239行，在运行_训练（cut_alpha=2.0，mix_alpha=1.0，num_classes=5）文件“D:\PycharmProject\MEMix\main.py”，第124行，在run_training中ALL, attn, final = net_all(mix_flow, onset)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\PycharmProject\MEMix\model.py”，第272行，向前x = 自我.模型(x,y) # [B,768]文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\PycharmProject\MEMix\model.py”，第201行，向前X = 自我.前进_特征(x,y)文件“D:\PycharmProject\MEMix\model.py”，第175行，在forward_features中X = 自我.补丁_嵌入(x)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\Anaconda3\envs\Mers\lib\site-packages\timm\layers\patch_embed.py”，第131行，向前X = 自我.proj(x)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1518行，在_wrapped_call_impl中返回自我._call_impl(*args, **kwargs)文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\module.py”，第1527行，在_call_impl中返回转发_呼叫（*args，**kwargs）文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py”，第460行，向前返回self._conv_forward（输入，自我.权重，自我.偏置）文件“D:\Anaconda3\envs\Mers\lib\site-packages\torch\nn\modules\conv.py”，第456行，在_conv_forward中返回F.conv2d（输入，重量，偏置，自我。步幅，运行时错误：给定组=1，大小权重[768，2，16，16]，预期输入[34，3，224，224]有2个通道，但得到了3个通道

我也遇到了这个问题，请问你是怎么解决的
